const data = {
    products:[
        {
            _id: '1',
            name: 'Very nice headears',
            category: 'computers',
            image: '/images.jpg',
            price: '420',
            countInStock: 10,
            brand: 'samsung',
            rating: 1.5,
            numReviews: 20,
            description: 'high quality product',
        },
        {
            _id: '2',
            name: 'Very nice shoes',
            category: 'computers',
            image: '/images.jpg',
            price: '20',
            countInStock: 20,
            brand: 'samsung',
            rating: 2.5,
            numReviews: 10,
            description: 'high quality product',
        },
        {
            _id: '3',
            name: 'Very nice T-shirt',
            category: 'computers',
            image: '/images.jpg',
            price: '120',
            countInStock: 30,
            brand: 'samsung',
            rating: 3.5,
            numReviews: 30,
            description: 'high quality product',
        },
        {
            _id: '4',
            name: 'Very nice jeans',
            category: 'computers',
            image: '/images.jpg',
            price: '220',
            countInStock: 40,
            brand: 'samsung',
            rating: 4.5,
            numReviews: 25,
            description: 'high quality product',
        },
        {
            _id: '5',
            name: 'Very nice boots',
            category: 'computers',
            image: '/images.jpg',
            price: '520',
            countInStock: 0,
            brand: 'samsung',
            rating: 5,
            numReviews: 45,
            description: 'high quality product',
        },
        {
            _id: '6',
            name: 'Very nice socks',
            category: 'computers',
            image: '/images.jpg',
            price: '620',
            countInStock: 0,
            brand: 'samsung',
            rating: 4,
            numReviews: 30,
            description: 'high quality product',
        },
    ],
};

export default data;